# Generated by Django 3.1.7 on 2021-06-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_auto_20210605_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='societyloan',
            name='full_name',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Societyloan',
        ),
    ]
