# Generated by Django 3.1.7 on 2021-06-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_member_societyloan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societyloan',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
