# Generated by Django 3.1.7 on 2021-06-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_remove_societyloan_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='societyloan',
            name='total_amount',
            field=models.FloatField(null=True),
        ),
    ]
