# Generated by Django 3.2.4 on 2021-06-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_auto_20210611_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='total_paid',
        ),
        migrations.AddField(
            model_name='loan',
            name='total_amounts',
            field=models.FloatField(default=True, null=True),
        ),
    ]
