# Generated by Django 3.2.4 on 2021-06-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_auto_20210611_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='remaining_balance',
        ),
        migrations.AddField(
            model_name='loan',
            name='total_paid',
            field=models.IntegerField(default=True),
        ),
    ]
