# Generated by Django 3.2.4 on 2021-06-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0017_societyloan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='total_paid',
        ),
    ]
