# Generated by Django 3.2.4 on 2021-06-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0018_remove_loan_total_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='societyloan',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='societyloan',
            name='start_month',
        ),
    ]
