# Generated by Django 3.2.4 on 2021-06-12 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0019_auto_20210612_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='month',
        ),
    ]
